//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_Inspection {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class CommonSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static CommonSetting defaultInstance = ((CommonSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CommonSetting())));
        
        public static CommonSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;database=toec_update;user=sartas;pwd=sartas;port=3306;CharSet=gb" +
            "2312;")]
        public string ConStr_Inspection {
            get {
                return ((string)(this["ConStr_Inspection"]));
            }
            set {
                this["ConStr_Inspection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office 2010 Silver")]
        public string SkinName {
            get {
                return ((string)(this["SkinName"]));
            }
            set {
                this["SkinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.1.10.88")]
        public string IP_Inspection {
            get {
                return ((string)(this["IP_Inspection"]));
            }
            set {
                this["IP_Inspection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string AlarmLevel {
            get {
                return ((string)(this["AlarmLevel"]));
            }
            set {
                this["AlarmLevel"] = value;
            }
        }
    }
}
